run:
  timeout: 5m
  go: "1.25"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - gosec
    - misspell
    - prealloc

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - style
  gosec:
    excludes:
      - G104

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
